version: "3.4"

services:
  server:
    image: ddjerqq/private:latest
    build: .
    container_name: server
    depends_on:
      - postgres
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    restart: always