version: "3.4"

services:
  server:
    image: server:latest
    build: .
    container_name: server
    depends_on:
      - postgres
    ports:
      - "443:443"
    restart: always

  postgres:
    image: postgres:latest
    build: .
    container_name: postgres
    ports:
      - "5432:5432"
      - "5555:5555"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    restart: always