name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Docker build
      run: |
        docker build . -t ddjerqq/private:latest

    - name: Docker push
      run: |
        docker push ddjerqq/private:latest


  test:
    runs-on: ubuntu-latest

    needs: build

    steps:

      - uses: actions/checkout@v3

      - name: Setup Database
        run: |
          pip install -r requirements.txt
          docker pull postgres:latest
          docker run --name postgres-test -e POSTGRES_PASSWORD=password -p5432:5432 -d postgres:latest
          python ./tests/setup_db.py

      - name: Run PyTests
        run: |
          pytest


  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:

      - uses: actions/checkout@v3

      - name: Restart docker-compose on the VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd work
            docker-compose down
            docker pull ddjerqq/private:latest
            docker-compose up -d