name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Docker build
      run: |
        docker build . -t mavefund/mavefun_api:latest

    - name: Docker push
      run: |
        docker push mavefund/mavefun_api:latest


#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#
#      - uses: actions/checkout@v3
#
#      - name: Run PyTests
#        run: |
#          pip install -r requirements.txt
#          pytest


  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:

      - uses: actions/checkout@v3

      - name: Restart docker-compose on the VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd work
            docker-compose down
            docker pull mavefund/mavefun_api:latest
            docker-compose up -d